function enter(m){sid=m.sessionId;token=m.token;app.innerHTML='<section class="card"><div class="row"><div><p id="course" style="color:#185dcb;font-weight:700;margin:0"></p><h1 id="clsname"></h1></div><button type="button" class="ghost" id="leave" style="width:auto">切换</button></div><p id="who"></p><div id="box"></div></section>';document.getElementById('leave').onclick=function(){save('classroom.current',null);sid=0;token='';boot();};poll();}
function left(q){return Math.max(0,Math.ceil((q.deadline-Date.now()-off)/1000));}
function poll(){if(!sid)return;api('/api/state',null,1).then(function(d){state=d;svc('已连通');draw();if(!d.session.ended)setTimeout(poll,2000);}).catch(function(e){svc('未连通');var b=document.getElementById('box');if(b)b.innerHTML='<p class="err">'+esc(e.message)+'</p>';setTimeout(poll,4000);});}
function draw(){if(!state)return;document.getElementById('course').textContent=state.session.course;document.getElementById('clsname').textContent=state.session.className;document.getElementById('who').textContent=state.name+' · '+state.studentId;var open=null,past=[];state.questions.forEach(function(q){if(q.open)open=q;else past.push(q);});var h='';if(state.session.ended)h+='<div class="wait"><h3>课堂已结束</h3></div>';else if(!open)h+='<div class="wait"><h3>等待老师开题</h3></div>';if(open)h+=qh(open,1);if(past.length){h+='<h2>记录</h2>';past.forEach(function(q){h+=qh(q,0);});}document.getElementById('box').innerHTML=h;var f=document.querySelector('form[data-qid]');if(f)f.onsubmit=function(e){e.preventDefault();var c=(f.querySelector('input:checked')||{}).value;if(!c){alert('请先选择');return;}api('/api/submit',{questionId:+f.getAttribute('data-qid'),choice:c},1).then(function(){return api('/api/state',null,1);}).then(function(d){state=d;draw();}).catch(function(err){alert(err.message);});};}
function qh(q,live){var n=left(q),can=live&&n>0&&!q.choice,h='<div style="border:1px solid #d8e1eb;border-radius:12px;padding:16px;margin:12px 0"><div class="row"><div class="qnum">'+q.lecture+'-'+q.number+'</div><div class="'+(can?'timer':'')+'">'+(can?n+'s':'已截止')+'</div></div>';if(q.choice)h+='<p class="ok">'+q.choice+'</p>';else if(can){h+='<form data-qid="'+q.id+'"><div class="choices">';String(q.options).split('').forEach(function(c){h+='<label><input type="radio" name="c" value="'+c+'"><span>'+c+'</span></label>';});h+='</div><button>提交</button></form>';}else h+='<p>未答</p>';if(q.answerKey)h+='<p><b>'+q.answerKey+'</b></p>';return h+'</div>';}
function boot(){joinUI([],'');document.getElementById('list').innerHTML='<p>正在查找班级…</p>';load().then(function(d){joinUI(d.sessions||[],'');}).catch(function(e){joinUI([],e.message);});}
var saved;try{saved=JSON.parse(localStorage.getItem('classroom.current'));}catch(e){}
if(saved&&mem[saved]&&mem[saved].token)enter(mem[saved]);else boot();
})();
